#define CANT_PARAM_CREAR_BASE 3
#define CANT_PARAM_DECO 2
#define SEPARADOR_FECHA '-'
#define SEPARADOR_LINEAS ','
#define CANT_CAMPOS 10


#define INIT_CHOP 4
#define CHOP_SIZE 4
#define ID_FIELD_POS 0
#define TITLE_FIELD_POS 1
#define SCRIPT_FIELD_POS 2
#define DIRECTOR_FIELD_POS 3
#define TIME_FIELD_POS 4
#define SCORE_FIELD_POS 7
#define REVIEWS_FIELD_POS 8

#define MAX_STR 50
#define POS_CREAR_BASE_DB 2
#define POS_CREAR_BASE_CSV 1


/* DECO */
#define FILE_DECO_POS 1
#define CANT_PELI_A_IMPRIMIR 1
#define CANT_TOTAL_CHAR_FECHA 10
#define CANT_CHAR_FECHA_ANIO 4
#define CANT_CHAR_FECHA_MES 2
#define CANT_CHAR_FECHA_DIA 2

/* RANKING */
#define CANT_TOTAL_PARAM_RANK 8
#define POS_COMMAND_CLA 1
#define CANT_ELEMENTOS_LEIDOS 1